### PR TITLE
security fix for parameters

### PR DESCRIPTION
**Pull request by vinas003**
Happy to talk about this further on email: victor (at) sunet.se

### CODE REVIEW

**Comment by enriquepablo** [comment]
Cool, thanks!

**Comment by vinas003** [comment]
Thanks, Will you update this to the production server or should we at sunet do it?

**Comment by enriquepablo** [comment]
I have added this to version 1.3.0rc10 which is a release candidate meant to be deployed today at staging, tested, and deployed to production as soon as Stefan approves (he's still on vacation until next week though).
It would also be possible to release a hotfix version patching the version currently in production if you'd prefer to sidestep staging.

**Comment by vinas003** [comment]
Ahh okey. Lets wait for Stefan then. Great work Enrique!

**Pull request merged**
